## Session #1 Homework

### Question 1

In [1]:
# What's the version of NumPy that you installed?
import numpy as np
np.__version__

'1.20.3'

### Question 2

In [2]:
# What's the version of Pandas?
import pandas as pd
pd.__version__

'1.3.2'

### Getting the data

In [3]:
data = pd.read_csv('car-price-data-ML ZoomCamp - Session 1.csv')
data.head()

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   
3  BMW    1 Series  2011  premium unleaded (required)      230.0   
4  BMW    1 Series  2011  premium unleaded (required)      230.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   
3               6.0            MANUAL  rear wheel drive              2.0   
4               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   
2                Luxury,High-Performance      Compact         Coupe   
3                     Luxury,Performance      Compact         Coupe   
4                                 Luxury      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350  
3           28        18        3916  29450  
4           28        18        3916  34500

### Question 3

In [4]:
# What's the average price of BMW cars in the dataset?
grouped_data = data.groupby('Make')['MSRP'].agg(['mean'])
grouped_data.loc['BMW']

mean    61546.763473
Name: BMW, dtype: float64

### Question 4

In [5]:
# Select a subset of cars after year 2015 (inclusive, i.e. 2015 and after). How many of them have missing values for Engine HP?
Year_after_2015 = (data[data.Year >= 2015]) 
missing_HP_after_2015 = Year_after_2015['Engine HP'].isnull().sum()
missing_HP_after_2015

51

### Question 5

In [7]:
# Calculate the average "Engine HP" in the dataset.
mean_hp_before = data['Engine HP'].mean()
print(round(mean_hp_before))

# Use the fillna method and to fill the missing values in "Engine HP" with the mean value from the previous step.
data['Engine HP'].fillna(mean_hp_before, inplace=True)

# Now, calcualte the average of "Engine HP" again.
mean_hp_after = data['Engine HP'].mean()
print(round(mean_hp_after))

# Has it changed?
# No Change

249
249


### Question 6

In [8]:
# Select all the "Rolls-Royce" cars from the dataset.
rolls_royce_data = data[data['Make'] == 'Rolls-Royce']

# Select only columns "Engine HP", "Engine Cylinders", "highway MPG".
select_rr = rolls_royce_data[['Engine HP','Engine Cylinders','highway MPG']]

# Now drop all duplicated rows using drop_duplicates method (you should get a dataframe with 7 rows).
unduplicated_rr = select_rr.drop_duplicates()

# Get the underlying NumPy array. Let's call it X.
X = unduplicated_rr.values
X

array([[325.,   8.,  15.],
       [563.,  12.,  19.],
       [563.,  12.,  21.],
       [563.,  12.,  20.],
       [322.,  12.,  15.],
       [453.,  12.,  19.],
       [624.,  12.,  21.]])

In [9]:
# Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
XTX = (X.T).dot(X)
XTX

array([[1.754801e+06, 3.965600e+04, 6.519600e+04],
       [3.965600e+04, 9.280000e+02, 1.500000e+03],
       [6.519600e+04, 1.500000e+03, 2.454000e+03]])

In [10]:
# Invert XTX.
inverse_XTX = np.linalg.inv(XTX)
inverse_XTX

array([[ 5.17815728e-05,  9.06587044e-04, -1.92984188e-03],
       [ 9.06587044e-04,  1.05723058e-01, -8.87084092e-02],
       [-1.92984188e-03, -8.87084092e-02,  1.05900809e-01]])

In [11]:
# What's the sum of all the elements of the result?
total = np.sum(inverse_XTX)
print(f'Sum of all the elements is {total}')

Sum of all the elements is 0.032212320677486195


### Questions 7

In [12]:
# Create an array y with values [1000, 1100, 900, 1200, 1000, 850, 1300].
y = np.array([1000, 1100, 900, 1200, 1000, 850, 1300])
y

# Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
#print(inverse_XTX * (X.T))
m = inverse_XTX.dot(X.T)
w = m.dot(y)
w
# What's the value of the first element of w?.
w[0]

0.19989598183186175